name: Python Environment

on:
  # To run manually
  workflow_dispatch
  push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
    
    - name: Install Python dependencies
      run: |
        python -m pip install matplotlib numpy rich

    - name: Hello World 
      run: |
        python -c "import numpy as np; import matplotlib as mpl; from rich.console import Console; from rich.panel import Panel; Console().print(Panel('Numpy version: '+np.__version__)+'\n'+'Matplotlib version: '+mpl.__version__)"
